sudo: required
language: node_js
node_js:
  - 10
env:
  global:
    - NODE_OPTIONS="--max_old_space_size=4096"
git:
  depth: 1
addons:
  apt:
    update: true
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
      - libsecret-1-dev
      - xvfb
      - libx11-dev
      - libxkbfile-dev
branches:
  only:
    - master
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.22.4
  - export PATH=$HOME/.yarn/bin:$PATH ;
before_script:
  - yarn --version
script:
  - npm i
  - npm run clean
  - npm run build
  - npm run audit || true
  - npm run parse
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: docs
  keep_history: true
  on:
    branch: master
